<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span></li></ul></div>

## Numpy

In [13]:
import numpy as np

scores = [89, 56, 76, 89, 98]
scores2 = [89, 56.72, 76, 89, 98]
scores3 = ["First", "Second", "Third"]

first_arr = np.array(scores)
second_arr = np.array(scores2)
third_arr = np.array(scores3)

print first_arr
print first_arr.dtype

print second_arr
print second_arr.dtype

print third_arr
print third_arr.dtype

[89 56 76 89 98]
int32
[89.   56.72 76.   89.   98.  ]
float64
['First' 'Second' 'Third']
|S6


In [21]:
# Nested List for creating multi diamensional array
scores_multi = [[34, 56, 23, 89], [11, 45, 76, 34]]
second_arr = np.array(scores_multi)

print second_arr
print second_arr.ndim
print second_arr.shape
print second_arr.dtype

[[34 56 23 89]
 [11 45 76 34]]
2
(2L, 4L)
int32


In [33]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
c = np.zeros((4, 3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
d = np.arange(15)  # sequential numbers
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
e = np.eye(6)  # Creates identit matrix
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
f = np.arange(12)
print f
print f[5]
print f[4:9]

f[4:9] = 99
print f

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5
[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]


In [47]:
modified_f = f[4:9]  # creating new modified array from existing array f
modified_f[1] = 1234  # change is made in new modified array
print f  # but these changes will be reflected in old array as well

[   0    1    2    3   99 1234   99   99   99    9   10   11]


In [48]:
# Array as Matrix
matrix_array = np.array([[3, 4, 5], [6, 7, 8], [9, 5, 1]])
print matrix_array
print matrix_array[1]
print matrix_array[0][2]
print matrix_array[0, 2]

[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5
5


In [57]:
print matrix_array[0:2, 0:2]

[[3 4]
 [6 7]]


In [64]:
print matrix_array[2]
print matrix_array[2,:]
print matrix_array[2,]
print matrix_array[-1]

[9 5 1]
[9 5 1]
[9 5 1]
[9 5 1]


In [68]:
print matrix_array[0:,0:2]

[[3 4]
 [6 7]
 [9 5]]


In [70]:
print matrix_array[1:2,0:2]

[[6 7]]


In [1]:
import numpy as np
thie = np.random.randn(5, 5)
print thie
print thie.mean()
print np.mean(thie)  # alterantive method calculating mean

[[ 1.55189726  0.40281407  0.68013921  0.16228503 -0.00617921]
 [-0.06992176 -0.26618597  0.05538884  1.26993908  1.254735  ]
 [-0.32976208 -0.03137167  3.13073605 -1.93851769  0.4649235 ]
 [-0.56170985 -0.96223434  1.28000599  0.99459927 -0.50810865]
 [-0.11929709 -1.31883347 -0.55542352  0.043874   -0.12520012]]
0.1799436747007878
0.1799436747007878


In [2]:
jp = np.arange(12).reshape(4, 3)
print "The array are:\n {}".format(jp)

The array are:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
print "sum of columns are: {}".format(np.sum(jp, axis=0))  # axis = 0 for sum of columns, axis =1 gives sum of rows
print "sum of rows are: {}".format(np.sum(jp, axis=1))  # axis = 0 for sum of columns, axis =1 gives sum of rows
print(jp.sum(0))
print(jp.sum(1))

sum of columns are: [18 22 26]
sum of rows are: [ 3 12 21 30]
[18 22 26]
[ 3 12 21 30]


In [4]:
lp = np.random.randn(5)
print lp
lp.sort()
print lp

[ 0.80824937  1.30871079  0.42606674  1.55192661 -0.01529934]
[-0.01529934  0.42606674  0.80824937  1.30871079  1.55192661]
